### ISSUE TITLE
Wrong Update in category named "Language and Communication"

### ISSUE THREAD

**Issue by boom210232** [Noboomta/KU-Table#19]
Hi, Puvana and teams
I think your web application is really useful for KU students.
And I see something that may be useful about how to count credits in an English course.
From the below link, they count the credits start with "Foundation English2".

Reference for more information: https://askme.registrar.ku.ac.th/ans/432.html
Hope my issue will be useful to your team.

**Comment by Noboomta** [comment]
Good afternoon Boom. 
Glad to see you here. Thank you for your information, we are looking for fixing this problem. It's gonna be fixed soon. Maybe we would bring the unit of Foundation English 1 out of the Lang- subject group. 

Thanks again. 
Puvana

**Comment by Noboomta** [comment]
Fixed it. Thankyou bro
