### ISSUE TITLE
PR Request: Currently working on Dark Mode.

### ISSUE THREAD

**Issue by GToidZ** [Noboomta/KU-Table#20]
ผมเป็นรุ่นน้องปี 1 SKE19 ครับ อยากจะเพิ่มฟีเจอร์ Dark Mode เข้าไปในตัวแอพ KU-Table ครับ ตอนนี้กำลังพัฒนาใน [Fork](https://github.com/GToidZ/KU-Table/tree/feature/dark-mode) เบื้องต้นยังไม่แน่ชัดว่าจะเสร็จวันไหนครับแต่จะลองดูครับ

**Comment by Noboomta** [comment]
ครับผม ขอบคุณครับ

**Comment by JAmoMES** [comment]
https://tailwindcss.com/docs/dark-mode

**Comment by Noboomta** [comment]
> https://tailwindcss.com/docs/dark-mode
> 
> 

Here we go again

**Comment by JAmoMES** [comment]
https://dev.to/tonyketcham/vue-tailwind-2-0-dark-mode-using-vuex-localstorage-and-user-s-default-preference-439g

**Comment by JAmoMES** [comment]
ลองดูพวกการทำ darkmode ของ tailwind น่าจะช่วยให้เขียนน้อยลงละโค้ดไม่ยาวมาก เรื่องการเก็บ theme น่าจะต้องไปยุ่งกับพวก localstorage ทางที่ดีถ้าพอทำเป็นลงพวก vuexให้ด้วยก็ดีไม่งั้นต้องเชคหลายหน้า

**Comment by Noboomta** [comment]
ต้องการ env หรืออะไรไปลองทักมาบอกได้นะๆ
